recipes:
   test:
      ingredients:
         0:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         1:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         2:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         3:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         4:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GLASS_BOTTLE
            amount: 1
         5:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         6:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         7:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         8:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
      product:
         ==: org.bukkit.inventory.ItemStack
         v: 2586
         type: GLASS_BOTTLE
         amount: 1
         meta:
            ==: ItemMeta
            custom-model-data: 666
            meta-type: UNSPECIFIC
            display-name: '{"text":"Citric Acid","italic":"false"}'