recipes:
  test:
    ingredients:
      0: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
      1: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
      2: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
      3: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
      4: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
      5: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
      6: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
      7: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
      8: 
        ==: org.bukkit.inventory.ItemStack
        type: "APPLE"
        amount: 1
    product:
      ==: org.bukkit.inventory.ItemStack
      type: "GLASS_BOTTLE"
      amount: 1