recipes:
   citric-acid:
      ingredients:
         0:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         1:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         2:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         3:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         4:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GLASS_BOTTLE
            amount: 1
         5:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         6:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         7:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         8:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: APPLE
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
      product:
         ==: org.bukkit.inventory.ItemStack
         v: 2586
         type: GLASS_BOTTLE
         amount: 1
         meta:
            ==: ItemMeta
            custom-model-data: 666
            meta-type: UNSPECIFIC
            display-name: '{"text":"Citric Acid","italic":"false"}'
      
   sulfuric-acid:
      ingredients:
         0:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: IRON_NUGGET
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         1:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: BLAZE_POWDER
            amount: 1
         2:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: IRON_NUGGET
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         3:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: BLAZE_POWDER
            amount: 1
            meta:
         4:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GLASS_BOTTLE
            amount: 1
         5:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: BLAZE_POWDER
            amount: 1
         6:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: IRON_NUGGET
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
         7:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: WATER_BUCKET
            amount: 1
         8:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: IRON_NUGGET
            amount: 1
            meta:
               ==: ItemMeta
               meta-type: UNSPECIFIC
               custom-model-data: 666
      product:
         ==: org.bukkit.inventory.ItemStack
         v: 2586
         type: GLASS_BOTTLE
         amount: 1
         meta:
            ==: ItemMeta
            custom-model-data: 667
            meta-type: UNSPECIFIC
            display-name: '{"text":"Sulfuric Acid","italic":"false"}'
      
   ethanol:
      ingredients:
         1:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: BROWN_MUSHROOM
            amount: 1
         4:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: WHEAT
            amount: 1
         7:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GLASS_BOTTLE
            amount: 1
      product:
         ==: org.bukkit.inventory.ItemStack
         v: 2586
         type: GLASS_BOTTLE
         amount: 1
         meta:
            ==: ItemMeta
            custom-model-data: 669
            meta-type: UNSPECIFIC
            display-name: '{"text":"Ethanol","italic":"false"}'
      
   potash:
      ingredients:
         1:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: OAK_LOG
            amount: 1
         4:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: WATER_BUCKET
            amount: 1
         7:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GLASS_BOTTLE
            amount: 1
      product:
         ==: org.bukkit.inventory.ItemStack
         v: 2586
         type: GLASS_BOTTLE
         amount: 1
         meta:
            ==: ItemMeta
            custom-model-data: 670
            meta-type: UNSPECIFIC
            display-name: '{"text":"Potassium Carbonate","italic":"false"}'
      
   calcium-hydroxide:
      ingredients:
         1:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: WATER_BUCKET
            amount: 1
         3:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: BLAZE_POWDER
            amount: 1
         4:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: NAUTILUS_SHELL
            amount: 1
         5:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: BLAZE_POWDER
            amount: 1
         7:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GLASS_BOTTLE
            amount: 1
      product:
         ==: org.bukkit.inventory.ItemStack
         v: 2586
         type: GLASS_BOTTLE
         amount: 1
         meta:
            ==: ItemMeta
            custom-model-data: 671
            meta-type: UNSPECIFIC
            display-name: '{"text":"Calcium Hydroxide","italic":"false"}'